[project]
name = "rerun-viz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pyrealsense2>=2.58.4.10922",
    "pyyaml>=6.0.3",
    "rerun-sdk>=0.37.2",
    "rosbags>=0.11.5",
    "scipy>=1.18.1",
    "tqdm>=4.70.1",
]
